version: "3.9"
services:
  web:
    container_name: apitest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    # environment:
    #   FLASK_ENV: development
  redis:
    image: "redis:alpine"
